apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
       name: nginx-2
       labels:
         name: myapp
         type: frontend
    spec:
       containers:
         - name: nginx
           image: nginx